name: vata
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ffmpeg
  - pip
  - pip:
    - torch>=2.6,<2.7
    - torchaudio>=2.6,<2.7
    - whisperx
    - pyannote.audio
    - ffmpeg-python
    - ollama
    - openai
    - typer[all]
    - rich
    - jinja2
    - python-dotenv
